_target_: pytorch_lightning.Trainer

gpus:
- 0

min_epochs: 1
max_epochs: 1
benchmark: True
check_val_every_n_epoch: 1
resume_from_checkpoint: null
gradient_clip_val: 0.0
limit_train_batches: 1
limit_val_batches: 1