model: "bce"
train:
  ext_name: 
    value: x3d_m
  block_type:
    value: linear
  rnn_type:
    value: lstm
  input_block:
    value: none
  output_block:
    value: same
  epochs:
    value: 200
  bias_rank:
    value: 1
  emb_dim:
    value: 12288
  hid_dim:
    value: 64
  # input_ranks:
  #   value: 
  # rnn_ranks:
  #   value: 
  # output_ranks:
  #   value: 
  experiments_name:  
    value: road_accidents
  patience:
    value: 10
  lr:
    value: 1e-3
  seed:
    value: 102

test:
  threshold_number:
    value: 25