train:
  ext_name: 
    value: x3d_m
  block_type:
    value: tcl3d
  epochs:
    value: 20
  bias_rank:
    values: [1, 2, 4, 8, -1]
  emb_dim:
    values: ["64,8,8", "128,8,8", "32,16,16", "64,16,16"]
  hid_dim:
    values: ["32,4,4", "64,4,4", "16,8,8", "32,8,8"]
  experiments_name:  
    values: [road_accidents, explosion]
  patience:
    value: 5

test:
  threshold_number:
    value: 25
