train:
  ext_name: 
    value: x3d_m
  block_type:
    value: linear 
  epochs:
    value: 200
  bias_rank:
    value: -1
  emb_dim:
    values: [12288]
  hid_dim:
    values: [4, 8, 16, 32, 64, 128, 256, 512]
  experiments_name:  
    values: [road_accidents, explosion]
  patience:
    value: 10
  seed:
    value: 102
test:
  threshold_number:
    value: 25
