model: "kl-cpd"
train:
  ext_name: 
    value: x3d_m
  block_type:
    value: tcl3d
  epochs:
    value: 500
  bias_rank:
    values: [1, 2, 4, 8, -1]
  emb_dim:
    values: ["32,8,8", "64,8,8", "128,8,8", "32,16,16", "64,16,16"]
  hid_dim:
    values: ["16,4,4", "32,4,4", "64,4,4", "16,8,8", "32,8,8"]
  experiments_name:  
    values: [road_accidents, explosion]

test:
  threshold_number:
    value: 25
  scales:
    value: [1e4, 3e4, 1e5, 3e5, 1e6, 3e6, 1e7]