model: "kl-cpd"
train:
  ext_name: 
    value: x3d_m
  block_type:
    value: linear
  epochs:
    value: 1
  bias_rank:
    value: 1
  emb_dim:
    value: 1000
  hid_dim:
    value: 100
  experiments_name:  
    value: road_accidents
  patience:
    value: 5
  lr:
    value: 1e-3
  seed:
    value: 102

test:
  threshold_number:
    value: 5
  scales:
    value: [1e4, 1e5]