train:
  ext_name: 
    value: x3d_m
  block_type:
    value: linear 
  epochs:
    value: 1
  bias_rank:
    values: [1]
  emb_dim:
    values: ["64,8,8"]
  hid_dim:
    values: ["32,4,4"]
  experiments_name:  
    values: [road_accidents]

test:
  threshold_number:
    value: 25
