model: "bce"
train:
  ext_name: 
    value: x3d_m
  block_type:
    value: linear
  rnn_type:
    value: lstm
  flatten_type:
    value: trl
  epochs:
    value: 1
  bias_rank:
    value: 1
  emb_dim:
    value: 12288
  hid_dim:
    value: 64
  experiments_name:  
    value: road_accidents
  patience:
    value: 5
  lr:
    value: 1e-3
  seed:
    value: 102

test:
  threshold_number:
    value: 5