model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss" 
  mode: "min"
  save_top_k: 1 
  save_last: True
  verbose: False
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  filename: '{epoch:02d}-{val_loss:.3f}'
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss" 
  mode: "min" 
  patience: 10
  min_delta: 0.000
  stopping_threshold: null