# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: base_datamodule.yaml
  - dataset: explosion.yaml
  - core_model: tda_lstm_lin_output.yaml
  - model: bce.yaml  
  - trainer: default.yaml
  - callbacks: null
  - logger: null

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

model_name: "bce"
# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, numpy and python.random
seed: 123

# passing checkpoint path is necessary
ckpt_path: ???

# specific for metrics calculation
with_add_mul: True