rnn_block_type: linear
data_dim: 12288
emb_dims: ${core_model.data_dim}
hidden_dims: 64
ranks_input: 1
ranks_output: 1
ranks_rnn: True

model_name: linear_lstm

model_description: 
  _target_: src.models.components.core_models.BceRNNTl
  input_block:
    _target_: src.models.components.base_cells.CoreBlock
    block_type: flatten
    input_dims: ${core_model.data_dim}
    hidden_dims: ${core_model.emb_dims}
    ranks: null 
    bias_rank: ${core_model.ranks_input}
    normalize: "both"
    block_place: "input"

  rnn_block:
    _target_: src.models.components.core_models.LayerNormLSTM
    input_size: ${core_model.emb_dims}
    hidden_size: ${core_model.hidden_dims}
    batch_first: True
    ln_type: "after"
        
  output_block:
    _target_: src.models.components.base_cells.CoreBlock
    block_type: linear
    input_dims: ${core_model.hidden_dims}
    hidden_dims: 1
    ranks: null
    bias_rank: ${core_model.ranks_output}
    normalize: "in"
    block_place: "output"
